// Code generated by syntaxgen; DO NOT EDIT.

package ast

import (
	"iter"

	"git.alberto.engineer/alberto/java-cst-go/syntax"
)

type CompilationUnit struct {
	node syntax.Node
}

func AsCompilationUnit(node syntax.Node) (CompilationUnit, bool) {
	if node.Kind() != syntax.KindNodeProgram {
		return CompilationUnit{}, false
	}
	return CompilationUnit{node: node}, true
}

func (value CompilationUnit) Node() syntax.Node {
	return value.node
}

type PackageDeclaration struct {
	node syntax.Node
}

func AsPackageDeclaration(node syntax.Node) (PackageDeclaration, bool) {
	if node.Kind() != syntax.KindNodePackageDeclaration {
		return PackageDeclaration{}, false
	}
	return PackageDeclaration{node: node}, true
}

func (value PackageDeclaration) Node() syntax.Node {
	return value.node
}

type ImportDeclaration struct {
	node syntax.Node
}

func AsImportDeclaration(node syntax.Node) (ImportDeclaration, bool) {
	if node.Kind() != syntax.KindNodeImportDeclaration {
		return ImportDeclaration{}, false
	}
	return ImportDeclaration{node: node}, true
}

func (value ImportDeclaration) Node() syntax.Node {
	return value.node
}

type ClassDeclaration struct {
	node syntax.Node
}

func AsClassDeclaration(node syntax.Node) (ClassDeclaration, bool) {
	if node.Kind() != syntax.KindNodeClassDeclaration {
		return ClassDeclaration{}, false
	}
	return ClassDeclaration{node: node}, true
}

func (value ClassDeclaration) Node() syntax.Node {
	return value.node
}

type InterfaceDeclaration struct {
	node syntax.Node
}

func AsInterfaceDeclaration(node syntax.Node) (InterfaceDeclaration, bool) {
	if node.Kind() != syntax.KindNodeInterfaceDeclaration {
		return InterfaceDeclaration{}, false
	}
	return InterfaceDeclaration{node: node}, true
}

func (value InterfaceDeclaration) Node() syntax.Node {
	return value.node
}

type EnumDeclaration struct {
	node syntax.Node
}

func AsEnumDeclaration(node syntax.Node) (EnumDeclaration, bool) {
	if node.Kind() != syntax.KindNodeEnumDeclaration {
		return EnumDeclaration{}, false
	}
	return EnumDeclaration{node: node}, true
}

func (value EnumDeclaration) Node() syntax.Node {
	return value.node
}

type AnnotationTypeDeclaration struct {
	node syntax.Node
}

func AsAnnotationTypeDeclaration(node syntax.Node) (AnnotationTypeDeclaration, bool) {
	if node.Kind() != syntax.KindNodeAnnotationTypeDeclaration {
		return AnnotationTypeDeclaration{}, false
	}
	return AnnotationTypeDeclaration{node: node}, true
}

func (value AnnotationTypeDeclaration) Node() syntax.Node {
	return value.node
}

type ClassBody struct {
	node syntax.Node
}

func AsClassBody(node syntax.Node) (ClassBody, bool) {
	if node.Kind() != syntax.KindNodeClassBody {
		return ClassBody{}, false
	}
	return ClassBody{node: node}, true
}

func (value ClassBody) Node() syntax.Node {
	return value.node
}

type InterfaceBody struct {
	node syntax.Node
}

func AsInterfaceBody(node syntax.Node) (InterfaceBody, bool) {
	if node.Kind() != syntax.KindNodeInterfaceBody {
		return InterfaceBody{}, false
	}
	return InterfaceBody{node: node}, true
}

func (value InterfaceBody) Node() syntax.Node {
	return value.node
}

type EnumBody struct {
	node syntax.Node
}

func AsEnumBody(node syntax.Node) (EnumBody, bool) {
	if node.Kind() != syntax.KindNodeEnumBody {
		return EnumBody{}, false
	}
	return EnumBody{node: node}, true
}

func (value EnumBody) Node() syntax.Node {
	return value.node
}

type EnumBodyDeclarations struct {
	node syntax.Node
}

func AsEnumBodyDeclarations(node syntax.Node) (EnumBodyDeclarations, bool) {
	if node.Kind() != syntax.KindNodeEnumBodyDeclarations {
		return EnumBodyDeclarations{}, false
	}
	return EnumBodyDeclarations{node: node}, true
}

func (value EnumBodyDeclarations) Node() syntax.Node {
	return value.node
}

type AnnotationTypeBody struct {
	node syntax.Node
}

func AsAnnotationTypeBody(node syntax.Node) (AnnotationTypeBody, bool) {
	if node.Kind() != syntax.KindNodeAnnotationTypeBody {
		return AnnotationTypeBody{}, false
	}
	return AnnotationTypeBody{node: node}, true
}

func (value AnnotationTypeBody) Node() syntax.Node {
	return value.node
}

type FieldDeclaration struct {
	node syntax.Node
}

func AsFieldDeclaration(node syntax.Node) (FieldDeclaration, bool) {
	if node.Kind() != syntax.KindNodeFieldDeclaration {
		return FieldDeclaration{}, false
	}
	return FieldDeclaration{node: node}, true
}

func (value FieldDeclaration) Node() syntax.Node {
	return value.node
}

type ConstantDeclaration struct {
	node syntax.Node
}

func AsConstantDeclaration(node syntax.Node) (ConstantDeclaration, bool) {
	if node.Kind() != syntax.KindNodeConstantDeclaration {
		return ConstantDeclaration{}, false
	}
	return ConstantDeclaration{node: node}, true
}

func (value ConstantDeclaration) Node() syntax.Node {
	return value.node
}

type MethodDeclaration struct {
	node syntax.Node
}

func AsMethodDeclaration(node syntax.Node) (MethodDeclaration, bool) {
	if node.Kind() != syntax.KindNodeMethodDeclaration {
		return MethodDeclaration{}, false
	}
	return MethodDeclaration{node: node}, true
}

func (value MethodDeclaration) Node() syntax.Node {
	return value.node
}

type ConstructorDeclaration struct {
	node syntax.Node
}

func AsConstructorDeclaration(node syntax.Node) (ConstructorDeclaration, bool) {
	if node.Kind() != syntax.KindNodeConstructorDeclaration {
		return ConstructorDeclaration{}, false
	}
	return ConstructorDeclaration{node: node}, true
}

func (value ConstructorDeclaration) Node() syntax.Node {
	return value.node
}

type StaticInitializer struct {
	node syntax.Node
}

func AsStaticInitializer(node syntax.Node) (StaticInitializer, bool) {
	if node.Kind() != syntax.KindNodeStaticInitializer {
		return StaticInitializer{}, false
	}
	return StaticInitializer{node: node}, true
}

func (value StaticInitializer) Node() syntax.Node {
	return value.node
}

type AnnotationTypeElementDeclaration struct {
	node syntax.Node
}

func AsAnnotationTypeElementDeclaration(node syntax.Node) (AnnotationTypeElementDeclaration, bool) {
	if node.Kind() != syntax.KindNodeAnnotationTypeElementDeclaration {
		return AnnotationTypeElementDeclaration{}, false
	}
	return AnnotationTypeElementDeclaration{node: node}, true
}

func (value AnnotationTypeElementDeclaration) Node() syntax.Node {
	return value.node
}

type EnumConstant struct {
	node syntax.Node
}

func AsEnumConstant(node syntax.Node) (EnumConstant, bool) {
	if node.Kind() != syntax.KindNodeEnumConstant {
		return EnumConstant{}, false
	}
	return EnumConstant{node: node}, true
}

func (value EnumConstant) Node() syntax.Node {
	return value.node
}

type VariableDeclarator struct {
	node syntax.Node
}

func AsVariableDeclarator(node syntax.Node) (VariableDeclarator, bool) {
	if node.Kind() != syntax.KindNodeVariableDeclarator {
		return VariableDeclarator{}, false
	}
	return VariableDeclarator{node: node}, true
}

func (value VariableDeclarator) Node() syntax.Node {
	return value.node
}

type FormalParameters struct {
	node syntax.Node
}

func AsFormalParameters(node syntax.Node) (FormalParameters, bool) {
	if node.Kind() != syntax.KindNodeFormalParameters {
		return FormalParameters{}, false
	}
	return FormalParameters{node: node}, true
}

func (value FormalParameters) Node() syntax.Node {
	return value.node
}

type FormalParameter struct {
	node syntax.Node
}

func AsFormalParameter(node syntax.Node) (FormalParameter, bool) {
	if node.Kind() != syntax.KindNodeFormalParameter {
		return FormalParameter{}, false
	}
	return FormalParameter{node: node}, true
}

func (value FormalParameter) Node() syntax.Node {
	return value.node
}

type SpreadParameter struct {
	node syntax.Node
}

func AsSpreadParameter(node syntax.Node) (SpreadParameter, bool) {
	if node.Kind() != syntax.KindNodeSpreadParameter {
		return SpreadParameter{}, false
	}
	return SpreadParameter{node: node}, true
}

func (value SpreadParameter) Node() syntax.Node {
	return value.node
}

type ReceiverParameter struct {
	node syntax.Node
}

func AsReceiverParameter(node syntax.Node) (ReceiverParameter, bool) {
	if node.Kind() != syntax.KindNodeReceiverParameter {
		return ReceiverParameter{}, false
	}
	return ReceiverParameter{node: node}, true
}

func (value ReceiverParameter) Node() syntax.Node {
	return value.node
}

type Block struct {
	node syntax.Node
}

func AsBlock(node syntax.Node) (Block, bool) {
	if node.Kind() != syntax.KindNodeBlock {
		return Block{}, false
	}
	return Block{node: node}, true
}

func (value Block) Node() syntax.Node {
	return value.node
}

type ConstructorBody struct {
	node syntax.Node
}

func AsConstructorBody(node syntax.Node) (ConstructorBody, bool) {
	if node.Kind() != syntax.KindNodeConstructorBody {
		return ConstructorBody{}, false
	}
	return ConstructorBody{node: node}, true
}

func (value ConstructorBody) Node() syntax.Node {
	return value.node
}

type TypeDeclaration struct {
	node syntax.Node
}

func AsTypeDeclaration(node syntax.Node) (TypeDeclaration, bool) {
	switch node.Kind() {
	case syntax.KindNodeClassDeclaration:
		return TypeDeclaration{node: node}, true
	case syntax.KindNodeInterfaceDeclaration:
		return TypeDeclaration{node: node}, true
	case syntax.KindNodeEnumDeclaration:
		return TypeDeclaration{node: node}, true
	case syntax.KindNodeAnnotationTypeDeclaration:
		return TypeDeclaration{node: node}, true
	default:
		return TypeDeclaration{}, false
	}
}

func (value TypeDeclaration) Node() syntax.Node {
	return value.node
}

func (value TypeDeclaration) Kind() syntax.Kind {
	return value.node.Kind()
}

func (value TypeDeclaration) AsClassDeclaration() (ClassDeclaration, bool) {
	return AsClassDeclaration(value.node)
}

func (value TypeDeclaration) AsInterfaceDeclaration() (InterfaceDeclaration, bool) {
	return AsInterfaceDeclaration(value.node)
}

func (value TypeDeclaration) AsEnumDeclaration() (EnumDeclaration, bool) {
	return AsEnumDeclaration(value.node)
}

func (value TypeDeclaration) AsAnnotationTypeDeclaration() (AnnotationTypeDeclaration, bool) {
	return AsAnnotationTypeDeclaration(value.node)
}

type MemberDeclaration struct {
	node syntax.Node
}

func AsMemberDeclaration(node syntax.Node) (MemberDeclaration, bool) {
	switch node.Kind() {
	case syntax.KindNodeFieldDeclaration:
		return MemberDeclaration{node: node}, true
	case syntax.KindNodeConstantDeclaration:
		return MemberDeclaration{node: node}, true
	case syntax.KindNodeMethodDeclaration:
		return MemberDeclaration{node: node}, true
	case syntax.KindNodeConstructorDeclaration:
		return MemberDeclaration{node: node}, true
	case syntax.KindNodeStaticInitializer:
		return MemberDeclaration{node: node}, true
	case syntax.KindNodeAnnotationTypeElementDeclaration:
		return MemberDeclaration{node: node}, true
	case syntax.KindNodeClassDeclaration:
		return MemberDeclaration{node: node}, true
	case syntax.KindNodeInterfaceDeclaration:
		return MemberDeclaration{node: node}, true
	case syntax.KindNodeEnumDeclaration:
		return MemberDeclaration{node: node}, true
	case syntax.KindNodeAnnotationTypeDeclaration:
		return MemberDeclaration{node: node}, true
	default:
		return MemberDeclaration{}, false
	}
}

func (value MemberDeclaration) Node() syntax.Node {
	return value.node
}

func (value MemberDeclaration) Kind() syntax.Kind {
	return value.node.Kind()
}

func (value MemberDeclaration) AsFieldDeclaration() (FieldDeclaration, bool) {
	return AsFieldDeclaration(value.node)
}

func (value MemberDeclaration) AsConstantDeclaration() (ConstantDeclaration, bool) {
	return AsConstantDeclaration(value.node)
}

func (value MemberDeclaration) AsMethodDeclaration() (MethodDeclaration, bool) {
	return AsMethodDeclaration(value.node)
}

func (value MemberDeclaration) AsConstructorDeclaration() (ConstructorDeclaration, bool) {
	return AsConstructorDeclaration(value.node)
}

func (value MemberDeclaration) AsStaticInitializer() (StaticInitializer, bool) {
	return AsStaticInitializer(value.node)
}

func (value MemberDeclaration) AsAnnotationTypeElementDeclaration() (AnnotationTypeElementDeclaration, bool) {
	return AsAnnotationTypeElementDeclaration(value.node)
}

func (value MemberDeclaration) AsClassDeclaration() (ClassDeclaration, bool) {
	return AsClassDeclaration(value.node)
}

func (value MemberDeclaration) AsInterfaceDeclaration() (InterfaceDeclaration, bool) {
	return AsInterfaceDeclaration(value.node)
}

func (value MemberDeclaration) AsEnumDeclaration() (EnumDeclaration, bool) {
	return AsEnumDeclaration(value.node)
}

func (value MemberDeclaration) AsAnnotationTypeDeclaration() (AnnotationTypeDeclaration, bool) {
	return AsAnnotationTypeDeclaration(value.node)
}

type Parameter struct {
	node syntax.Node
}

func AsParameter(node syntax.Node) (Parameter, bool) {
	switch node.Kind() {
	case syntax.KindNodeFormalParameter:
		return Parameter{node: node}, true
	case syntax.KindNodeSpreadParameter:
		return Parameter{node: node}, true
	case syntax.KindNodeReceiverParameter:
		return Parameter{node: node}, true
	default:
		return Parameter{}, false
	}
}

func (value Parameter) Node() syntax.Node {
	return value.node
}

func (value Parameter) Kind() syntax.Kind {
	return value.node.Kind()
}

func (value Parameter) AsFormalParameter() (FormalParameter, bool) {
	return AsFormalParameter(value.node)
}

func (value Parameter) AsSpreadParameter() (SpreadParameter, bool) {
	return AsSpreadParameter(value.node)
}

func (value Parameter) AsReceiverParameter() (ReceiverParameter, bool) {
	return AsReceiverParameter(value.node)
}

func (value CompilationUnit) Package() (PackageDeclaration, bool) {
	for child := range value.node.ChildNodes() {
		if result, ok := AsPackageDeclaration(child); ok {
			return result, true
		}
	}
	return PackageDeclaration{}, false
}

func (value CompilationUnit) Imports() iter.Seq[ImportDeclaration] {
	return func(yield func(ImportDeclaration) bool) {
		for child := range value.node.ChildNodes() {
			if result, ok := AsImportDeclaration(child); ok && !yield(result) {
				return
			}
		}
	}
}

func (value CompilationUnit) ImportsSlice() []ImportDeclaration {
	var result []ImportDeclaration
	for item := range value.Imports() {
		result = append(result, item)
	}
	return result
}

func (value CompilationUnit) Types() iter.Seq[TypeDeclaration] {
	return func(yield func(TypeDeclaration) bool) {
		for child := range value.node.ChildNodes() {
			if result, ok := AsTypeDeclaration(child); ok && !yield(result) {
				return
			}
		}
	}
}

func (value CompilationUnit) TypesSlice() []TypeDeclaration {
	var result []TypeDeclaration
	for item := range value.Types() {
		result = append(result, item)
	}
	return result
}

func (value ClassDeclaration) Name() (syntax.Token, bool) {
	for token := range value.node.ChildTokens() {
		if token.Kind() == syntax.KindTokenIdentifier {
			return token, true
		}
	}
	return syntax.Token{}, false
}

func (value ClassDeclaration) Body() (ClassBody, bool) {
	for child := range value.node.ChildNodes() {
		if result, ok := AsClassBody(child); ok {
			return result, true
		}
	}
	return ClassBody{}, false
}

func (value InterfaceDeclaration) Name() (syntax.Token, bool) {
	for token := range value.node.ChildTokens() {
		if token.Kind() == syntax.KindTokenIdentifier {
			return token, true
		}
	}
	return syntax.Token{}, false
}

func (value InterfaceDeclaration) Body() (InterfaceBody, bool) {
	for child := range value.node.ChildNodes() {
		if result, ok := AsInterfaceBody(child); ok {
			return result, true
		}
	}
	return InterfaceBody{}, false
}

func (value EnumDeclaration) Name() (syntax.Token, bool) {
	for token := range value.node.ChildTokens() {
		if token.Kind() == syntax.KindTokenIdentifier {
			return token, true
		}
	}
	return syntax.Token{}, false
}

func (value EnumDeclaration) Body() (EnumBody, bool) {
	for child := range value.node.ChildNodes() {
		if result, ok := AsEnumBody(child); ok {
			return result, true
		}
	}
	return EnumBody{}, false
}

func (value AnnotationTypeDeclaration) Name() (syntax.Token, bool) {
	for token := range value.node.ChildTokens() {
		if token.Kind() == syntax.KindTokenIdentifier {
			return token, true
		}
	}
	return syntax.Token{}, false
}

func (value AnnotationTypeDeclaration) Body() (AnnotationTypeBody, bool) {
	for child := range value.node.ChildNodes() {
		if result, ok := AsAnnotationTypeBody(child); ok {
			return result, true
		}
	}
	return AnnotationTypeBody{}, false
}

func (value ClassBody) Members() iter.Seq[MemberDeclaration] {
	return func(yield func(MemberDeclaration) bool) {
		for child := range value.node.ChildNodes() {
			if result, ok := AsMemberDeclaration(child); ok && !yield(result) {
				return
			}
		}
	}
}

func (value ClassBody) MembersSlice() []MemberDeclaration {
	var result []MemberDeclaration
	for item := range value.Members() {
		result = append(result, item)
	}
	return result
}

func (value InterfaceBody) Members() iter.Seq[MemberDeclaration] {
	return func(yield func(MemberDeclaration) bool) {
		for child := range value.node.ChildNodes() {
			if result, ok := AsMemberDeclaration(child); ok && !yield(result) {
				return
			}
		}
	}
}

func (value InterfaceBody) MembersSlice() []MemberDeclaration {
	var result []MemberDeclaration
	for item := range value.Members() {
		result = append(result, item)
	}
	return result
}

func (value AnnotationTypeBody) Members() iter.Seq[MemberDeclaration] {
	return func(yield func(MemberDeclaration) bool) {
		for child := range value.node.ChildNodes() {
			if result, ok := AsMemberDeclaration(child); ok && !yield(result) {
				return
			}
		}
	}
}

func (value AnnotationTypeBody) MembersSlice() []MemberDeclaration {
	var result []MemberDeclaration
	for item := range value.Members() {
		result = append(result, item)
	}
	return result
}

func (value EnumBody) Constants() iter.Seq[EnumConstant] {
	return func(yield func(EnumConstant) bool) {
		for child := range value.node.ChildNodes() {
			if result, ok := AsEnumConstant(child); ok && !yield(result) {
				return
			}
		}
	}
}

func (value EnumBody) ConstantsSlice() []EnumConstant {
	var result []EnumConstant
	for item := range value.Constants() {
		result = append(result, item)
	}
	return result
}

func (value EnumBody) Declarations() (EnumBodyDeclarations, bool) {
	for child := range value.node.ChildNodes() {
		if result, ok := AsEnumBodyDeclarations(child); ok {
			return result, true
		}
	}
	return EnumBodyDeclarations{}, false
}

func (value EnumBodyDeclarations) Members() iter.Seq[MemberDeclaration] {
	return func(yield func(MemberDeclaration) bool) {
		for child := range value.node.ChildNodes() {
			if result, ok := AsMemberDeclaration(child); ok && !yield(result) {
				return
			}
		}
	}
}

func (value EnumBodyDeclarations) MembersSlice() []MemberDeclaration {
	var result []MemberDeclaration
	for item := range value.Members() {
		result = append(result, item)
	}
	return result
}

func (value MethodDeclaration) Name() (syntax.Token, bool) {
	for token := range value.node.ChildTokens() {
		if token.Kind() == syntax.KindTokenIdentifier {
			return token, true
		}
	}
	return syntax.Token{}, false
}

func (value MethodDeclaration) Parameters() (FormalParameters, bool) {
	for child := range value.node.ChildNodes() {
		if result, ok := AsFormalParameters(child); ok {
			return result, true
		}
	}
	return FormalParameters{}, false
}

func (value MethodDeclaration) Body() (Block, bool) {
	for child := range value.node.ChildNodes() {
		if result, ok := AsBlock(child); ok {
			return result, true
		}
	}
	return Block{}, false
}

func (value ConstructorDeclaration) Name() (syntax.Token, bool) {
	for token := range value.node.ChildTokens() {
		if token.Kind() == syntax.KindTokenIdentifier {
			return token, true
		}
	}
	return syntax.Token{}, false
}

func (value ConstructorDeclaration) Parameters() (FormalParameters, bool) {
	for child := range value.node.ChildNodes() {
		if result, ok := AsFormalParameters(child); ok {
			return result, true
		}
	}
	return FormalParameters{}, false
}

func (value ConstructorDeclaration) Body() (ConstructorBody, bool) {
	for child := range value.node.ChildNodes() {
		if result, ok := AsConstructorBody(child); ok {
			return result, true
		}
	}
	return ConstructorBody{}, false
}

func (value VariableDeclarator) Name() (syntax.Token, bool) {
	for token := range value.node.ChildTokens() {
		if token.Kind() == syntax.KindTokenIdentifier {
			return token, true
		}
	}
	return syntax.Token{}, false
}

func (value FormalParameter) Name() (syntax.Token, bool) {
	for token := range value.node.ChildTokens() {
		if token.Kind() == syntax.KindTokenIdentifier {
			return token, true
		}
	}
	return syntax.Token{}, false
}

func (value SpreadParameter) Name() (syntax.Token, bool) {
	for token := range value.node.ChildTokens() {
		if token.Kind() == syntax.KindTokenIdentifier {
			return token, true
		}
	}
	return syntax.Token{}, false
}

func (value ReceiverParameter) Name() (syntax.Token, bool) {
	for token := range value.node.ChildTokens() {
		if token.Kind() == syntax.KindTokenIdentifier {
			return token, true
		}
	}
	return syntax.Token{}, false
}

func (value FieldDeclaration) Declarators() iter.Seq[VariableDeclarator] {
	return func(yield func(VariableDeclarator) bool) {
		for child := range value.node.ChildNodes() {
			if result, ok := AsVariableDeclarator(child); ok && !yield(result) {
				return
			}
		}
	}
}

func (value FieldDeclaration) DeclaratorsSlice() []VariableDeclarator {
	var result []VariableDeclarator
	for item := range value.Declarators() {
		result = append(result, item)
	}
	return result
}

func (value ConstantDeclaration) Declarators() iter.Seq[VariableDeclarator] {
	return func(yield func(VariableDeclarator) bool) {
		for child := range value.node.ChildNodes() {
			if result, ok := AsVariableDeclarator(child); ok && !yield(result) {
				return
			}
		}
	}
}

func (value ConstantDeclaration) DeclaratorsSlice() []VariableDeclarator {
	var result []VariableDeclarator
	for item := range value.Declarators() {
		result = append(result, item)
	}
	return result
}

func (value FormalParameters) Items() iter.Seq[Parameter] {
	return func(yield func(Parameter) bool) {
		for child := range value.node.ChildNodes() {
			if result, ok := AsParameter(child); ok && !yield(result) {
				return
			}
		}
	}
}

func (value FormalParameters) ItemsSlice() []Parameter {
	var result []Parameter
	for item := range value.Items() {
		result = append(result, item)
	}
	return result
}
