// Code generated by syntaxgen; DO NOT EDIT.

package syntax

const (
	KindNodeProgram                          Kind = "node:program"
	KindNodePackageDeclaration               Kind = "node:package_declaration"
	KindNodeImportDeclaration                Kind = "node:import_declaration"
	KindNodeClassDeclaration                 Kind = "node:class_declaration"
	KindNodeInterfaceDeclaration             Kind = "node:interface_declaration"
	KindNodeEnumDeclaration                  Kind = "node:enum_declaration"
	KindNodeAnnotationTypeDeclaration        Kind = "node:annotation_type_declaration"
	KindNodeClassBody                        Kind = "node:class_body"
	KindNodeInterfaceBody                    Kind = "node:interface_body"
	KindNodeEnumBody                         Kind = "node:enum_body"
	KindNodeEnumBodyDeclarations             Kind = "node:enum_body_declarations"
	KindNodeAnnotationTypeBody               Kind = "node:annotation_type_body"
	KindNodeFieldDeclaration                 Kind = "node:field_declaration"
	KindNodeConstantDeclaration              Kind = "node:constant_declaration"
	KindNodeMethodDeclaration                Kind = "node:method_declaration"
	KindNodeConstructorDeclaration           Kind = "node:constructor_declaration"
	KindNodeStaticInitializer                Kind = "node:static_initializer"
	KindNodeAnnotationTypeElementDeclaration Kind = "node:annotation_type_element_declaration"
	KindNodeEnumConstant                     Kind = "node:enum_constant"
	KindNodeVariableDeclarator               Kind = "node:variable_declarator"
	KindNodeFormalParameters                 Kind = "node:formal_parameters"
	KindNodeFormalParameter                  Kind = "node:formal_parameter"
	KindNodeSpreadParameter                  Kind = "node:spread_parameter"
	KindNodeReceiverParameter                Kind = "node:receiver_parameter"
	KindNodeBlock                            Kind = "node:block"
	KindNodeConstructorBody                  Kind = "node:constructor_body"
	KindTokenIdentifier                      Kind = "token:identifier"
)
